# Generated by Django 5.1.3 on 2025-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_job_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', '信息技术与软件'), ('Retail', '零售与销售'), ('Education', '教育与辅导'), ('Hospitality', '酒店与服务行业'), ('Other', '其他')], max_length=50),
        ),
    ]
